from zoneinfo import ZoneInfo

ET_TIMEZONE = ZoneInfo("America/New_York")
MARKET_CLOSE_MINUTES = 16 * 60 + 15  # 4:15 PM ET

EOD_PRICE_TOOLS: frozenset[str] = frozenset({
    "historical-price-eod-light",
})

FORBIDDEN_FMP_TOOLS: frozenset[str] = frozenset({
    "COT-report",
    "COT-report-analysis",
    "COT-report-list",
    "acquisition-ownership",
    "aftermarket-quote",
    "aftermarket-trade",
    "all-commodities-quotes",
    "all-cryptocurrency-quotes",
    "all-forex-quotes",
    "all-index-quotes",
    "all-transaction-types",
    "average-directional-index",
    "batch-quote",
    "batch-quote-short",
    "country-weighting",
    "crowdfunding-search",
    "disclosures-dates",
    "disclosures-name-search",
    "dow-jones",
    "equity-offering-by-cik",
    "equity-offering-search",
    "esg-benchmark",
    "esg-ratings",
    "esg-search",
    "etf-asset-exposure",
    "grades",
    "grades-summary",
})

PRIORITY_FMP_TOOLS: frozenset[str] = frozenset({
    "8k-latest",
    "as-reported-balance-statements",
    "as-reported-cashflow-statements",
    "as-reported-financial-statements",
    "as-reported-income-statements",
    "balance-sheet-statement",
    "balance-sheet-statement-growth",
    "balance-sheet-statements-ttm",
    "cashflow-statement",
    "cashflow-statement-growth",
    "cashflow-statements-ttm",
    "financial-reports-form-10-k-json",
    "financial-reports-form-10-k-xlsx",
    "financial-statement-growth",
    "financials-latest",
    "form-13f-filings-dates",
    "general-news",
    "income-statement",
    "income-statement-growth",
    "income-statements-ttm",
    "revenue-geographic-segments",
    "revenue-product-segmentation",
    "stock-news",
    "company-executives",
    "dividends-calendar",
    "dividends-company",
    "earnings-calendar",
    "earnings-company",
    "financial-reports-dates",
    "fmp-articles",
    "information",
    "profile-symbol",
    "employee-count",
    "executive-compensation",
    "key-metrics",
    "key-metrics-ttm",
    "market-cap",
    "metrics-ratios",
    "metrics-ratios-ttm",
    "company-notes",
    "historical-industry-pe",
    "historical-industry-performance",
    "historical-market-cap",
    "historical-price-eod-dividend-adjusted",
    "historical-price-eod-full",
    "historical-price-eod-light",
    "historical-sector-pe",
    "historical-sector-performance",
    "latest-filings",
    "latest-financial-statements",
    "latest-mergers-acquisitions",
    "industry-performance-snapshot",
    "industry-PE-snapshot",
    "sector-PE-snapshot",
    "historical-employee-count",
    "sector-performance-snapshot",
    "ipos-calendar",
    "ipos-disclosure",
    "ipos-prospectus",
})
